### ISSUE TITLE
mobs not dropping loot, at all

### ISSUE THREAD

**Issue by absinth3** [Tigereye504/chestcavity#109]
So, I'm playing on a 1.20.1 server, with the 1.20.1-2.16.6 forge port of Chest Cavity, up until now I've no been having any issues, but I noticed that entities like sheep, cows etc. don't drop either their usual loot, organs or even experience, organs or enchants do not come at play here, I tried resetting my cavity, still no loot, killed with an empty eq and an unenchanted vanilla weapon? no loot.

Is this a config, server, version or client issue? If anything, what can I do to solve it? I don't know whether or not the bit of log showcasing the issue is required, so I'll post it in the reply below

**Comment by absinth3** [comment]
and here's the beast of the log bit, it occurs for every entity hostile or not that I have killed :/

 [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundInteractPacket@1a413b0c, suppressing error
java.lang.NullPointerException: Cannot invoke "java.util.function.Consumer.accept(Object)" because "p_287569_" is null
	at net.minecraft.world.level.storage.loot.LootTable.m_287134_(LootTable.java:58) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.handler$zbl000$generateUnprocessedLootMixin_ModifyPopulatedListAndFeedConsumer(LootTable.java:548) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.m_79131_(LootTable.java:93) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:117) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.m_287276_(LootTable.java:96) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.world.entity.LivingEntity.m_7625_(LivingEntity.java:1411) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.world.entity.Mob.m_7625_(Mob.java:502) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6668_(LivingEntity.java:1368) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6667_(LivingEntity.java:1327) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1182) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.world.entity.animal.Animal.m_6469_(Animal.java:76) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.world.entity.player.Player.m_5706_(Player.java:1139) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.server.level.ServerPlayer.m_5706_(ServerPlayer.java:1400) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_141994_(ServerGamePacketListenerImpl.java:1489) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.m_142457_(ServerboundInteractPacket.java:166) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_179617_(ServerboundInteractPacket.java:66) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6946_(ServerGamePacketListenerImpl.java:1457) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:53) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:13) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by absinth3** [comment]
ok....after some trial and error from me and other players.. JUST the mobs affected by chest cavity... rest do just fine
