### ISSUE TITLE
"Ticking memory connection", Worked earlier removed a few mods (not ones required) started crashing

### ISSUE THREAD

**Issue by StellarDreemurr** [Tigereye504/chestcavity#35]
---- Minecraft Crash Report ----
// My bad.

Time: 4/26/21 2:43 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at net.tigereye.chestcavity.chestcavities.instance.ChestCavityInstance.handler$zzf000$scoreCheck(ChestCavityInstance.java:535)
	at net.tigereye.chestcavity.chestcavities.instance.ChestCavityInstance.getOrganScore(ChestCavityInstance.java:84)
	at net.tigereye.chestcavity.listeners.OrganUpdateListeners.UpdateAppendix(OrganUpdateListeners.java:33)
	at net.tigereye.chestcavity.listeners.OrganUpdateListeners$$Lambda$2321/250289324.onOrganUpdate(Unknown Source)
	at net.tigereye.chestcavity.listeners.OrganUpdateCallback.lambda$static$0(OrganUpdateCallback.java:12)
	at net.tigereye.chestcavity.listeners.OrganUpdateCallback$$Lambda$2320/278465074.onOrganUpdate(Unknown Source)
	at net.tigereye.chestcavity.util.ChestCavityUtil.organUpdate(ChestCavityUtil.java:457)
	at net.tigereye.chestcavity.util.ChestCavityUtil.evaluateChestCavity(ChestCavityUtil.java:354)
	at net.tigereye.chestcavity.chestcavities.instance.ChestCavityInstance.<init>(ChestCavityInstance.java:56)
	at net.tigereye.chestcavity.chestcavities.instance.ChestCavityInstanceFactory.newChestCavityInstance(ChestCavityInstanceFactory.java:21)
	at net.minecraft.class_1309.handler$zdp000$chestCavityLivingEntityConstructorMixin(class_1309.java:4362)
	at net.minecraft.class_1309.<init>(class_1309.java:234)
	at net.minecraft.class_1657.<init>(class_1657.java:199)
	at net.minecraft.class_3222.<init>(class_3222.java:185)
	at net.minecraft.class_3324.method_14613(class_3324.java:461)
	at net.minecraft.class_3248.method_14384(class_3248.java:113)
	at net.minecraft.class_3248.redirect$zlk000$handlePlayerJoin(class_3248.java:562)
	at net.minecraft.class_3248.method_18785(class_3248.java:65)
	at net.minecraft.class_2535.method_10754(class_2535.java:228)
	at net.minecraft.class_3242.method_14357(class_3242.java:173)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$5114/1260302110.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by eehunter** [comment]
This appears to be an issue with one of the mixins in my mod, Rise of the Toasters. It may or may not be resolved in the latest update of RotT (1.1.5), but either way this issue should be closed as it isn't a problem with Chest Cavity.
